# Generated by Django 5.1.5 on 2025-02-04 14:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('DB', '0005_remove_keystrokedata___keypress_mean_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='KeystrokeData',
        ),
    ]
